# This is a basic workflow to help you get started with Actions

name: judge lean3

on:
  repository_dispatch:
    types: [lean3]

jobs:
  judge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Lean 3
        run: | 
          wget -q https://raw.githubusercontent.com/leanprover-community/mathlib-tools/master/scripts/install_debian.sh && bash install_debian.sh ; rm -f install_debian.sh && source ~/.profile
          leanpkg configure
          leanproject get-mathlib-cache
        
      - name: Judge 
        continue-on-error: true
        run: npm run start
