name: Judge Lean 3

on:
  repository_dispatch:
    types: [lean3]
  workflow_dispatch:

jobs:
  judge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Cache Lean 3
        id: cache-lean3
        uses: actions/cache@v3
        with:
          path: |
            ~/.elan
            ~/.profile
            ~/.mathlib
            _target
          key: ${{ runner.os }}-cache-lean3-mathlib3-${{ hashFiles('**/leanpkg.toml') }}

      - name: Cache NPM
        uses: actions/cache@v3
        id: cache-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - if: ${{ steps.cache-lean3.outputs.cache-hit != 'true' }}
        name: Setup Lean 3
        run: |
          wget https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh
          bash elan-init.sh -y
          rm elan-init.sh
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          . ~/.profile
          pipx install mathlibtools
          leanpkg configure
          leanproject get-mathlib-cache
      
      - name: Setup Node Packages
        run: npm install

      - name: Judge
        env:
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
          SUBMISSION_ID: ${{ github.event.client_payload.submission_id }}
          JUDGER_SECRET: ${{ secrets.JUDGER_SECRET }}
        run: |
          source ~/.profile
          npm run start
      
