# This is a basic workflow to help you get started with Actions

name: judge lean3

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [lean3]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  judge:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Lean 3
        run: |
          wget https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh
          bash elan-init.sh -y
          rm elan-init.sh
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          . ~/.profile
          pipx install mathlibtools
          source ~/.profile

      - name: Configure Lean
        run: |
          source ~/.profile
          leanpkg configure
          leanproject get-mathlib-cache

      # Runs a set of commands using the runners shell
      - name: Setup source code file
        run: |
          printf '%s' "${{ github.event.client_payload.defs }}" > defs.lean
          printf '%s' "${{ github.event.client_payload.submission }}" > submission.lean
          printf '%s' "${{ github.event.client_payload.check }}" > check.lean

      - name: Lean 
        continue-on-error: true
        run: |
          source ~/.profile
          lean --version
          lean check.lean -E check.out --old-oleans --json --only-export=main 2>>err.log 1>>out.log
          leanchecker check.out main 2>>err.log 1>>out.log

      - name: Upload out.log
        uses: actions/upload-artifact@v3.1.2
        with:
          name: out.log 
          path: out.log

      - name: Upload err.log
        uses: actions/upload-artifact@v3.1.2
        with:
          name: err.log
          path: err.log

      
