# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [lean3]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  judge:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup Lean 3
        run: wget -q https://raw.githubusercontent.com/leanprover-community/mathlib-tools/master/scripts/install_debian.sh && bash install_debian.sh ; rm -f install_debian.sh && source ~/.profile

      # Runs a set of commands using the runners shell
      - name: Setup source code file
        env: 
          code: ${{ github.event.client_payload.code }}
        run: echo "$code" > sol.lean && cat sol.lean
        
      - name: Lean 
        run:
          lean --make sol.lean 2>err.log 1>out.log

      - name: Upload out.log
        uses: actions/upload-artifact@v3.1.2
        with:
          name: out.log 
          path: out.log

      - name: Upload err.log
        uses: actions/upload-artifact@v3.1.2
        with:
          name: err.log
          path: err.log

      
